name: Build BrenmaxOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            make
            nasm
            mingw-w64-x86_64-gcc

      - name: Build
        shell: msys2 {0}
        run: |
          make compiler=gcc objcopy=objcopy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrenmaxOS
          path: BrenmaxOS.img

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}
          files: BrenmaxOS.img
